version: '3.4'

services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile


  shoppingcart:
    image: ${DOCKER_REGISTRY-}shoppingcart
    build:
      context: .
      dockerfile: ShoppingCart/Dockerfile


  ordering:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: Ordering/Dockerfile

